### ISSUE TITLE
"res" and "spec_res" could have better names

### ISSUE THREAD

**Issue by andreufont** [sbird/fake_spectra#12]
These are both arguments in the constructor of Spectra class, and they can be a bit confusing. 

It would be great if "res" was renamed "pixel_width" or similar. 

It got worse because until now @keirkwame was using his variable "spectrum_resolution" in lyman_alpha repo to feed "spec", and not "spec_res".

**Comment by andreufont** [comment]
HI @sbird - Yes, the documentation is now clearer, although it says that spec_res is the FWHM and I believe it is the Gaussian rms. At least that is how it is used in the _window_function function. I would also specify the units (km/s).

I also noticed that until now the default was spec_res=8 km/s, what probably means that the optical depth rescaling was not correct. I'm not sure how much this would affect ongoing projects (emulators or the tests by @Chris-Pedersen), but it is probably worth re-running these.

**Comment by sbird** [comment]
@andreufont : Indeed! The optical depth rescaling was not correct, especially because we were setting the BOSS spectrograph value of spec_res = 69 in the emulator project. This was exactly the change for which I re-ran the emulator spectra the other day!

Documentation should be corrected when I get to somewhere that git push works.

Incidentally, the gaussian smoothing is applied to the flux, not the optical depth, can you confirm that this is correct?

**Comment by andreufont** [comment]
Yes, the smoothing should be applied to flux.

**Comment by sbird** [comment]
Cheers. Closing, with doc change push pending.
